### PR TITLE
feat(ClassCard): display class colors

### LINKED ISSUE #2: Add event color to ClassCard
Add event color as stripe on the left side of ClassCard, and fill the entire card with that color if that class is selected. (Plus if it has a sexy animation when selecting it)

### PR DESCRIPTION
**Pull request by AdrianAndersen**
Resolves #2 

### Before
image

### After
https://user-images.githubusercontent.com/26925695/214243522-1a962688-e04e-4866-ac64-63ac36702502.mov

### CODE REVIEW

**Comment by AdrianAndersen** [comment]
@mathiazom

**Comment by AdrianAndersen** [comment]
@mathiazom now it is animated! 😄 

The colors are a bit off sometimes, but I think keying the specific colors can be done later. Agree?

**Comment by mathiazom** [comment]
@AdrianAndersen Have you looked into moving `<Collapse />` below the card content?

**Comment by AdrianAndersen** [comment]
Yeah, I tested it, but it produces some interesting results. When it is below CardContent, it only covers CardAction when expanded. This is because the Collapse has position absolute. 

Also tested with different zIndex for the Collapse and CardContent, but it did not affect the design at all 👀

**Comment by mathiazom** [comment]
Resolved by #6

**Pull request closed without merging**
